apiVersion: batch/v1
kind: Job
metadata:
  name: pg-backup
  labels:
    app: flask1
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postgres
          image: srinidocker003/check:4.0
          env:
            - name: PGPASSWORD
              value: 'Admin'
          command: ["pg_dump","-U","postgres","-h","postgres","postgres"]
          volumeMounts:
            - mountPath: "/pg_backup"
              name: backup-volume
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: pg-backup-pvc
