---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "srinidocker003/lab-test:10"
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: backup-storage
spec:
  storageClassName: "local"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
spec:
  storageClassName: "local"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi




